config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  resources :tickets do 
    collection do
      get :addtecnico
    end
  end
  
  get 'static_pages/landing_page'
  root to: "static_pages#landing_page"
  
  devise_for :users
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :assign_default_role
  accepts_nested_attributes_for :roles,
    allow_destroy: true,
    reject_if: ->(hash){ hash["_keep"] != "1" }
  has_many :tickets
  
  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:tecnico)
    else
      self.add_role(:usuario)
    end
  end

  def self.create_new_user(params)
    @user = User.create!(params)
  end

  def to_s
    email
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update]

    def index
        @users = User.all.order(created_at: :desc)
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to users_path, notice: 'El usuario ha sido actualizado'
        else
          render 'edit'
        end
    end

    def new
        @user = User.new(user_params)
        if @user.save
            redirect_to users_path, notice: "User succesfully created!" 
        else
            render :new
        end
    end
    
    def create
        @user = User.new(params[:user])
        if @user.save
          redirect_to users_path
        else
          render :new
        end
    end

    def show
        sign_out :user
        redirect_to static_pages_landing_page_path
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
    
        if @user.destroy
            redirect_to root_url, notice: "User deleted."
        end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end 

    def user_params
        params.permit(:email, :name, :last_name, :roles, :password, :password_confirmation)
    end

    def user_params
        params.require(:user).permit({role_ids: []})
    end

    def update_params
        user_params.tap do |o|
          # Adds the _delete attribute if the keep checkbox is unchecked
          o[:roles_attributes] = o[:roles_attributes].map do |k,h|
             attrs = h.merge(_destroy: (h[:_keep] != "1"))
             # Don't let the user update the name of an existing Role!
             # This would let a malicious user to grant any role.
             h.key?(:id) ? attrs.except(:name) : attrs 
          end
        end
    end
end

app/views/users/_form.html.haml
= form_for User.create, as: resource_name do |f| 
    .field
        = f.label :name
        %br/
        = f.text_field :name
    .field
        = f.label :email
        %br/
        = f.email_field :email, autofocus: true
    .field
        = f.label :password
        %br/
        = f.password_field :password, autocomplete: "off"
    .field
        = f.label :password_confirmation
        %br/
        = f.password_field :password_confirmation, autocomplete: "off"
    .field
        = f.select(:roles) do
            - [['Admin', "admin"], ['Usuario', "usuario"], ['Tecnico', "tecnico"]].each do |c|
                = content_tag(:option, c.first, value: c.last)
    .actions
        = f.submit "Sign up"

app/views/users/_user.html.haml
.container
    - if current_user.has_role? :admin
        = link_to new_user_path , class: 'btn-primary btn-lg' do 
            %i.fa.fa-user-plus
        .card
            %header.card-header
                %p.card-header-title
                    = user.name
                %button.card-header-icon{"aria-label" => "more options"}
                    %span.icon
                        %i.fas.fa-angle-down{"aria-hidden" => "true"}
            .card-content
                .content
                    Este usuario esta registrado desde
                    = time_ago_in_words(user.created_at)
                    %br/
                    %time{:datetime => user.created_at} 
            %footer.card-footer
                -user.roles.each do |role|
                    %span.tag.is-primary 
                        = role.name
                %a.card-footer-item{:href => edit_user_path(user)} Edit
                = link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" }, class: "card-footer-item"
            

app/views/users/edit.html.haml
.container
    .card
        .card-header
            Editando usuario 
            = @user.email
        .card-body 
            = simple_form_for @user do |f|
                = f.collection_check_boxes :role_ids, Role.all, :id, :name
                = f.error :roles, class: 'text-danger'
                %hr
                = f.button :submit, class: 'btn btn-success'
        .card-footer
        =link_to 'cancelar', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
.card-columns 
    - @users.each do |user|
        =render 'users/user', user: user
= search_form_for @q do |f|
    = f.search_field :email_cont
    = f.submit
= link_to users_path, class: 'btn btn-sm btn-secondary' do
    .fa.fa-referre 
%table.table.table-bordered
    %thead 
        %tr     
            %th id 
            %th Mail 
            %th Creacion 
            %th Nombre
    %tbody
        - @users.each do |user|
            %tr
                %td= user.id
                %td= user.email 
                %td= user.created_at 
                %td= user.name

app/views/users/new.html.haml
.card-columns 
    =render 'users/form'