config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  resources :tickets do 
    collection do
      get :addtecnico
    end
  end
  
  get 'static_pages/landing_page'
  root to: "static_pages#landing_page"
  
  devise_for :users
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    extend SimpleCalendar
    validates :title,   :presence => true
                    
    validates :description, :presence => true
    validates :estados, presence: true
    validate :overlapping_appointments
    validates :telefono,    :numericality => true,
                            on: :create,
                            :length => { :minimum => 10, :maximum => 15, :message => "El Telefono debe tener 10 caracteres" }
    validate :check_dates

    belongs_to :user
    has_many :users
    has_one_attached :images
    
    def check_dates
        if self.starts_at.present?
            a = self.starts_at
            errors.add(:starts_at, "La cita no puede ser en el pasado") if( a < Time.now)
        end
    end

    def initialize(params={})
        super(params)
    end

    def start_time
        self.starts_at
    end

    def overlapping_appointments
        if (Ticket.where("(? BETWEEN starts_at AND ends_at OR ? BETWEEN starts_at AND ends_at) AND user_id = ?", self.starts_at, self.ends_at, self.user_id).any?)
           errors.add(:ends_at, 'Se empalma con otra reserva')
        end
    end

    def to_s
        title
    end 
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  # GET /tickets or /tickets.json
  def index
    if current_user.has_any_role? :admin
      @tickets = Ticket.all
    else
      @tickets = Ticket.where(:user_id => current_user.id)
    end
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    tickets = Ticket.find(params[:id])
  end

  # GET /tickets/new
  def new
    @tickets = Ticket.all
    @ticket = Ticket.new
  end

  def set_n
    tickets = Ticket.find(params[:id])
    if tickets.params[:remoto] = true
      tickets.params[:starts_at] = null
      tickets.params[:ends_at] = null
    end
  end
  # GET /tickets/1/edit
  def edit
    @users = User.all
  end

  # POST /tickets or /tickets.json
  def create
    @users = User.all
    @user = current_user
    @tickets = Ticket.all
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @starts_at = params[:starts_at]

      if @ticket.save 
        redirect_to @ticket, notice: "Se creo el ticket correctamente"
      else
        render :new, status: :unprocessable_entity
      end
  end

  def addtecnico
    ticket = Ticket.find(params[:id])
    @ticket.users << User.find(params[:user_id])
    respond_to do |format|
      format.html { redirect_to @ticket, :notice => 'Added.' }
    end
  end

  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def count_status
    @ticket = Ticket.where(estados: 'Pendiente')
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :estados, :remoto, :direccion, :starts_at, :ends_at, :telefono, :images, images: [], users: [] ) 
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_calendario.html.haml
= month_calendar events: @tickets do |date, tickets|
  = date
  - tickets.each do |ticket|
    %div
      = ticket.title

app/views/tickets/_cita.html.haml
%h1 nueva citaa

app/views/tickets/_form.html.haml
.container
  = form_for @ticket do |f|
    - if @ticket.errors.any?
      #error_explanation
        %h2= "#{pluralize(@ticket.errors.count, "error/es")} Prohiben que se cree el ticket"
        .alert.alert-danger{:role => "alert"}
          - @ticket.errors.full_messages.each do |message|
            %li= message    
  .card
    %header.card-header
      %p.card-header-title Ticket Nuevo
    .card-content
    - if current_user.has_any_role? :admin, :tecnico
      .content       
        = form_for @ticket do |f|
          .field
            %label.label Titulo
            %label.label{:id => 'titulo'}
            .control
              = f.text_field :title, :id => 'titu', :class => 'input', :onkeyup => 'hNull()'
          :javascript
              function hNull() {
                var tit = document.getElementById('titu').value;
                var boton = document.getElementById('boton')
                var err1 = document.getElementById('titulo')
                if( tit == ''){
                  err1.innerHTML = "<span style='color: red;'>"+
                  " Titulo obligatorio </span>"
                  boton.disabled = true;
                }else {
                  err1.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field
            %label.label Problema(Descripcion)
            %label.label{:id => 'problema'}
            .control
              = f.text_area :description, :id => 'descripcion', :class => 'textarea', :onkeyup => 'pNull()'
          :javascript
              function pNull() {
                var desc = document.getElementById('descripcion').value;
                var boton = document.getElementById('boton')
                var err2 = document.getElementById('problema')
                if( desc == ''){
                  err2.innerHTML = "<span style='color: red;'>"+
                  " Descripcion obligatorio obligatorio</span>"
                  boton.disabled = true;
                }else {
                  err2.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field{:id => 'tel'} 
            %label.label Telefono
            %label.label{:id => 'label2'}
            .control
              = f.text_field :telefono, :class => 'input', :id => 'tele', :onkeypress => "validate(event)", :onkeyup => 'tNull()'
          :javascript
            function tNull() {
              var val = document.getElementById('tele').value;
              var boton = document.getElementById('boton')
              var campo = document.getElementById('tel')
              var err3 = document.getElementById('label2')
              if(val == ""){
                campo.style.borderColor = "red";
                err3.innerHTML = "<span style='color: red;'>"+
                "El telefono No puede estar vacio</span>";
                  } else if (val.length !== 10){
                    campo.style.borderColor = "red";
                    err = err3.innerHTML = "<span style='color: red;'>"+
                    "El telefono debe tener 10 digitos</span>"
                  }else {
                    err = err3.innerHTML = "<span style='color: red;'>"+
                    "</span>"
                  }
                  return err
              }
            function validate(evt) {
              var theEvent = evt || window.event;

              // Handle paste
              if (theEvent.type === 'paste') {
                  key = event.clipboardData.getData('text/plain');
              } else {
              // Handle key press
                  var key = theEvent.keyCode || theEvent.which;
                  key = String.fromCharCode(key);
              }
              var regex = /[0-9]|\./;
              if( !regex.test(key) ) {
                theEvent.returnValue = false;
                if(theEvent.preventDefault) theEvent.preventDefault();
              }
            }
 
          .field
            %label.label Direccion
            %label.label{:id => 'direc'}
            .control
              = f.text_field :direccion, :class => 'input',:id => 'direccion', :onkeyup => 'dNull()'
          :javascript
              function dNull() {
                var dire = document.getElementById('direccion').value;
                var boton = document.getElementById('boton')
                var aviso = document.getElementById('direc')
                if(dire == ''){
                  aviso.innerHTML = "<span style='color: red;'>"+
                  " direccion obligatorio</span>"
                }else {
                  aviso.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field
            %label.label Marca esta casilla si requieres de servicio remoto
            .control 
              = f.check_box :remoto,{}, :class => 'checkbox', :id => 'dateCheck'
          .field{:id => 'start'}
            %label.label Selecciona una fecha y hora de inicio
            %label.label{:id => 'label'}
            .control
              .columns
                .column{:id => 'test'}
                  = f.datetime_field :starts_at, :class => 'form-control datepicker', :style => "\r\n    border-bottom-width: 1px;\r\n    margin-bottom: 20px;", :id => 'date'
          :javascript
            var checkbox = document.getElementById('ticket_remoto');
            var details_div = document.getElementById('start');
            checkbox.onchange = function() {
                if(this.checked == false) {
                details_div.style['display'] = 'block';
                } else {
                details_div.style['display'] = 'none';
                }
            };
          .file.has-name.is-boxed
            %label.file-label 
              Sube una Imagen relacionada a tu problema
              = f.file_field :images, :class => 'file-input'
              %span.file-cta
                %span.file-icon
                  %i.fas.fa-upload
                %span.file-label
                  Escoge un archivo            
          .actions
            %label.label{:id => 'aviso'}
            = f.submit 'Enviar', :disabled => "disabled", :class => 'button is-link', :id => 'boton', :onclick => "checkDate()"
            :javascript
              function checkDate() {
                var selectedText = document.getElementById('date').value;
                var field = document.getElementById('date')
                var selectedDate = new Date(selectedText);
                var goodDate = selectedDate.getDate()
                var boton = document.getElementById('boton')
                var error = document.getElementById('aviso')
                var now = new Date();
                var gd = now.getDate()
                var fecha = document.getElementById('date').value;
                var fechaSelec = new Date(fecha);
                var tiempo = fechaSelec.getHours();
                var ahora = new Date();
                var horaAhora = ahora.getHours();
                if (((goodDate < gd) || (tiempo < horaAhora)) && selectedText == '') {
                  field.style.borderColor = "red";
                  error.innerHTML = "<span style='color: red;'>"+
                  "Ingresa una fecha/hora valida o llene el campo</span>"
                  boton.disabled = true;
                }
                else if(goodDate == gd){
                  field.style.borderColor = "green";
                  error.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                }
              }
            = link_to 'Atras', tickets_path, :class => 'button is-link is-light'
    - else  
      .content
        .field
          = ticket.title
        .field
          = ticket.description 
        .field
          = ticket.estados

app/views/tickets/_normal.html.haml
.container
  = form_for @ticket do |f|
    - if @ticket.errors.any?
      #error_explanation
        %h2= "#{pluralize(@ticket.errors.count, "error/es")} Prohiben que se cree el ticket"
        .alert.alert-danger{:role => "alert"}
          - @ticket.errors.full_messages.each do |message|
            %li= message    
  .card
    %header.card-header
      %p.card-header-title Ticket Nuevo
    .card-content
      .content       
        = form_for @ticket do |f|
          .field
            %label.label Titulo
            %label.label{:id => 'titulo'}
            .control
              = f.text_field :title, :id => 'titu', :class => 'input', :onkeyup => 'hNull()'
          :javascript
              function hNull() {
                var tit = document.getElementById('titu').value;
                var boton = document.getElementById('boton')
                var err1 = document.getElementById('titulo')
                if( tit == ''){
                  err1.innerHTML = "<span style='color: red;'>"+
                  " Titulo obligatorio </span>"
                  boton.disabled = true;
                }else {
                  err1.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field
            %label.label Problema(Descripcion)
            %label.label{:id => 'problema'}
            .control
              = f.text_area :description, :id => 'descripcion', :class => 'textarea', :onkeyup => 'pNull()'
          :javascript
              function pNull() {
                var desc = document.getElementById('descripcion').value;
                var boton = document.getElementById('boton')
                var err2 = document.getElementById('problema')
                if( desc == ''){
                  err2.innerHTML = "<span style='color: red;'>"+
                  " Descripcion obligatorio obligatorio</span>"
                  boton.disabled = true;
                }else {
                  err2.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field{:id => 'tel'} 
            %label.label Telefono
            %label.label{:id => 'label2'}
            .control
              = f.text_field :telefono, :class => 'input', :id => 'tele', :onkeypress => "validate(event)", :onkeyup => 'tNull()'
          :javascript
            function tNull() {
              var val = document.getElementById('tele').value;
              var boton = document.getElementById('boton')
              var campo = document.getElementById('tel')
              var err3 = document.getElementById('label2')
              if(val == ""){
                campo.style.borderColor = "red";
                err3.innerHTML = "<span style='color: red;'>"+
                "El telefono No puede estar vacio</span>";
                  } else if (val.length !== 10){
                    campo.style.borderColor = "red";
                    err = err3.innerHTML = "<span style='color: red;'>"+
                    "El telefono debe tener 10 digitos</span>"
                  }else {
                    err = err3.innerHTML = "<span style='color: red;'>"+
                    "</span>"
                  }
                  return err
              }
            function validate(evt) {
              var theEvent = evt || window.event;

              // Handle paste
              if (theEvent.type === 'paste') {
                  key = event.clipboardData.getData('text/plain');
              } else {
              // Handle key press
                  var key = theEvent.keyCode || theEvent.which;
                  key = String.fromCharCode(key);
              }
              var regex = /[0-9]|\./;
              if( !regex.test(key) ) {
                theEvent.returnValue = false;
                if(theEvent.preventDefault) theEvent.preventDefault();
              }
            }
 
          .field
            %label.label Direccion
            %label.label{:id => 'direc'}
            .control
              = f.text_field :direccion, :class => 'input',:id => 'direccion', :onkeyup => 'dNull()'
          :javascript
              function dNull() {
                var dire = document.getElementById('direccion').value;
                var boton = document.getElementById('boton')
                var aviso = document.getElementById('direc')
                if(dire == ''){
                  aviso.innerHTML = "<span style='color: red;'>"+
                  " direccion obligatorio</span>"
                }else {
                  aviso.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                  boton.disabled = false;
                }
              }
          .field
            %label.label Marca esta casilla si requieres de servicio remoto
            .control 
              = f.check_box :remoto,{}, :class => 'checkbox', :id => 'dateCheck'
          .field{:id => 'start'}
            %label.label Selecciona una fecha y hora de inicio
            %label.label{:id => 'label'}
            .control
              .columns
                .column{:id => 'test'}
                  = f.datetime_field :starts_at, :class => 'form-control datepicker', :style => "\r\n    border-bottom-width: 1px;\r\n    margin-bottom: 20px;", :id => 'date'
          
          %button.btn.btn-primary{"data-bs-target" => "#exampleModal", "data-bs-toggle" => "modal", :type => "button"}
            %label.label Disponibilidad
          #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
            .modal-dialog
              .modal-content{:style => "width: 952px;height: 802px;;margin-right: -;margin-right: 0px;border-right-width: 0px;right: 200px;"}
                .modal-header
                  %h5#exampleModalLabel.modal-title Disponibilidad 
                  %button.btn-close{"aria-label" => "Cerrar", "data-bs-dismiss" => "modal", :type => "button"}
                .modal-body
                  = render 'tickets/calendario', tickets: @tickets
                .modal-footer
                  %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Cerrar
          :javascript
            var checkbox = document.getElementById('ticket_remoto');
            var details_div = document.getElementById('start');
            checkbox.onchange = function() {
                if(this.checked == false) {
                details_div.style['display'] = 'block';
                } else {
                details_div.style['display'] = 'none';
                }
            };
          .file.has-name.is-boxed
            %label.file-label 
              Sube una Imagen relacionada a tu problema
              = f.file_field :images, :class => 'file-input'
              %span.file-cta
                %span.file-icon
                  %i.fas.fa-upload
                %span.file-label
                  Escoge un archivo            
          .actions
            %label.label{:id => 'aviso'}
            = f.submit 'Enviar', :disabled => "disabled", :class => 'button is-link', :id => 'boton', :onclick => "checkDate()"
            :javascript
              function checkDate() {
                var selectedText = document.getElementById('date').value;
                var field = document.getElementById('date')
                var selectedDate = new Date(selectedText);
                var goodDate = selectedDate.getDate()
                var boton = document.getElementById('boton')
                var error = document.getElementById('aviso')
                var now = new Date();
                var gd = now.getDate()
                var fecha = document.getElementById('date').value;
                var fechaSelec = new Date(fecha);
                var tiempo = fechaSelec.getHours();
                var ahora = new Date();
                var horaAhora = ahora.getHours();
                if (((goodDate < gd) || (tiempo < horaAhora)) && selectedText == '') {
                  field.style.borderColor = "red";
                  error.innerHTML = "<span style='color: red;'>"+
                  "Ingresa una fecha/hora valida o llene el campo</span>"
                  boton.disabled = true;
                }
                else if(goodDate == gd){
                  field.style.borderColor = "green";
                  error.innerHTML = "<span style='color: red;'>"+
                  "</span>"
                }
              }
            = link_to 'Atras', tickets_path, :class => 'button is-link is-light'
          

app/views/tickets/_talone.html.haml
.container
    .card
        .card-header
            = ticket.title
        .card-content
            .media-content
                %p.title.is-4
                    %strong Descripcion:
                    = @ticket.description  
                %p.subtitle.is-6
                    %strong Estado del ticket:
                    = @ticket.estados
                - if @ticket.starts_at.present? and @ticket.ends_at.present?
                    %article.message.is-danger
                        .message-header
                            %p Cita generada correctamente
                            %button.delete{"aria-label" => "delete"}
                        .message-body
                            %p Su cita se genero con el folio
                            = @ticket.id
                            %p En la siguiente fecha: 
                            = @ticket.starts_at.strftime("%-d/%-m/%y: %H:%M %Z")
            .media
                .media-left
                    %figure.image.is-50x50
                        = image_tag(@ticket.images, style: 'width:30%;') if @ticket.images.attached?
        .card-footer
            .card-footer-item 
                .far.fa-clock 
                = ticket.created_at.strftime('%d-%b-%Y')
            .card-footer-item
                .fa.fa-chalkboard-teacher 
                = ticket.user_id
        = link_to 'Atras', tickets_path, :class => 'button is-link is-light'
        - if current_user.has_any_role? :admin, :tecnico
            = link_to 'Editar', edit_ticket_path(ticket), class: 'btn btn-sm btn-warning' 

app/views/tickets/_ticket.html.haml
.container
    .card
        .card-header
            = ticket.title
        .card-content
            .content
                = ticket.description
                = ticket.estados
        .card-footer
            .card-footer-item 
                .far.fa-clock 
                = ticket.created_at.strftime('%d-%b-%Y')
            .card-footer-item
                .fa.fa-chalkboard-teacher 
                = ticket.user
        = link_to 'Mostrar', ticket, class: 'btn btn-sm btn-primary'
        - if current_user.has_any_role? :admin, :tecnico
            = link_to 'Editar', edit_ticket_path(ticket), class: 'btn btn-sm btn-warning' 

app/views/tickets/edit.html.haml
%h1 Editar ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
%h1
  .columns
    .column 
      = link_to 'Ticket Nuevo', new_ticket_path, :class => 'button is-warning'
    -if current_user.has_role? :admin
      .column
        Tickets:
        = @tickets.count
    -else
      .column
        Tickets:
        = Ticket.where(:user_id => current_user.id).count
- if current_user.has_role? :admin
  .columns
    .column
      - @tickets.each do |ticket|
        = render 'tickets/ticket', ticket: ticket
- else 
  .columns
    .column
      - Ticket.where(:user_id => current_user.id).each do |ticket|
        = render 'tickets/ticket', ticket: ticket
%br

app/views/tickets/new.html.haml
-if current_user.has_any_role? :admin
    = render 'form'
- else
    = render 'normal', tickets: @ticket
    

app/views/tickets/show.html.haml
=render 'tickets/talone', ticket: @ticket