config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  resources :tickets do 
    collection do
      get :addtecnico
    end
  end
  
  get 'static_pages/landing_page'
  root to: "static_pages#landing_page"
  
  devise_for :users
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates :titulo, presence: true
    validates :descripcion, presence: true
    validates :precio, presence: true

    has_many_attached :images
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @products = Product.all.with_attached_images
  end

  # GET /products/1 or /products/1.json
  def show
    @products = Product.with_attached_images.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:titulo, :precio, :descripcion, :images)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :titulo
    = f.text_field :titulo
  .field
    = f.label :precio
    = f.text_field :precio
  .field
    = f.label :descripcion
    = f.text_field :descripcion
  .field
    = f.label :imagen
    = f.file_field :images
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %thead
    %tr
      %th Titulo
      %th Precio
      %th Descripcion
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.titulo
        %td= product.precio
        %td= product.descripcion
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }


%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Titulo:
  = @product.titulo
%p
  %b Precio:
  = @product.precio
%p
  %b Descripcion:
  = @product.descripcion
%p 
  %b  
  =@product.images.each do |images|
    = image_tag(@product.images)

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path