config/routes.rb
Rails.application.routes.draw do
  resources :products
  
  resources :tickets do 
    collection do
      get :addtecnico
    end
  end
  
  get 'static_pages/landing_page'
  root to: "static_pages#landing_page"
  
  devise_for :users
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
- if current_user
    = current_user.email    
    %nav.navbar.navbar-light.bg-light
        .row.align-items-start{:href => "#"}
            %a{:href => ""}
            %img{:alt => "Our Agenda App Logo", :src => "#{asset_path "teratech.png"}"}/
        / end logo
        .d-grid.gap-2.d-md-flex.justify-content-md-end
            = link_to edit_user_registration_path, class: 'btn-warning btn-lg' do 
                %i.fa.fa-cog
            = link_to destroy_user_session_path, class: 'btn-info btn-lg' do 
                %i.fa.fa-sign-out-alt
            = link_to tickets_path, class: 'btn-primary btn-lg' do 
                %i.fa.fa-ticket-alt
            -if current_user.has_role? :admin
                = link_to users_path, class: 'btn-secondary btn-lg' do 
                    %i.fa.fa-user
    / end nav
    / end header
- else
    .d-grid.gap-2.d-md-flex.justify-content-md-end
        %a.btn.btn-warning{"aria-disabled" => "true", :href => new_user_session_path} Iniciar sesion
        %a.btn.btn-success{"aria-disabled" => "true", :href => new_user_registration_path} Registro 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TeraTech
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_pack_tag 'application'
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
  %body
    = render 'layouts/header'
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    %p.notice= notice
    %p.alert= alert
    = yield